/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    enquiries: Enquiry;
    contacts: Contact;
    bookings: Booking;
    'revenue-entries': RevenueEntry;
    'customer-activities': CustomerActivity;
    'email-templates': EmailTemplate;
    'email-messages': EmailMessage;
    'follow-ups': FollowUp;
    'follow-up-rules': FollowUpRule;
    'incoming-replies': IncomingReply;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'revenue-entries': RevenueEntriesSelect<false> | RevenueEntriesSelect<true>;
    'customer-activities': CustomerActivitiesSelect<false> | CustomerActivitiesSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'email-messages': EmailMessagesSelect<false> | EmailMessagesSelect<true>;
    'follow-ups': FollowUpsSelect<false> | FollowUpsSelect<true>;
    'follow-up-rules': FollowUpRulesSelect<false> | FollowUpRulesSelect<true>;
    'incoming-replies': IncomingRepliesSelect<false> | IncomingRepliesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User;
  jobs: {
    tasks: {
      simulateFollowUp: TaskSimulateFollowUp;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Search by filename or alt text; filter by visibility. JPEG, PNG, WebP or AVIF, up to 20 MiB. Open an image for dimensions and details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for people who cannot see it.
   */
  alt: string;
  /**
   * Only explicitly public images can appear on the website.
   */
  visibility: 'private' | 'public';
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Save a first draft to enable Live Preview. Preview changes are unsaved until Save Draft; only Publish makes them public.
   */
  layout: (HeroBlock | TextBlock | GalleryBlock | ImageTextBlock | ServicesBlock | CallToActionBlock)[];
  title: string;
  /**
   * The page address. Use home for the home page.
   */
  slug: string;
  description: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  /**
   * Choose an image. Private images appear only in editor previews.
   */
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  heading: string;
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  heading: string;
  images?:
    | {
        /**
         * Choose an image. Private images appear only in editor previews.
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  heading: string;
  body: string;
  /**
   * Choose an image. Private images appear only in editor previews.
   */
  image: number | Media;
  imageSide: 'left' | 'right';
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  heading: string;
  body?: string | null;
  items: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  body?: string | null;
  label: string;
  /**
   * Use / or an existing page path such as /sessions. No external URLs.
   */
  href: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * Private enquiry queue. Review each new enquiry and follow up manually. Preview visitor emails are never sent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  /**
   * Link to an existing contact only after checking identity. Matching email alone is not sufficient.
   */
  contact?: (number | null) | Contact;
  serviceId: string;
  serviceTitle: string;
  name: string;
  email: string;
  message: string;
  /**
   * Manual follow-up only. No booking or availability is created.
   */
  followUp: 'new' | 'contacted' | 'closed';
  submissionHash: string;
  contentHash: string;
  /**
   * Immutable submission snapshot for future booking/revenue linkage. Optional identifiers are absent without campaign consent.
   */
  attribution:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notificationStatus: 'pending' | 'sending' | 'accepted' | 'failed' | 'disabled' | 'manual';
  notificationAttempts: number;
  notificationAttemptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private contact records. Matching email addresses are not automatically merged.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Private operational notes. Do not record sensitive personal information.
   */
  notes?: string | null;
  sourceKey?: string | null;
  /**
   * Stops every planned follow-up for this customer, including test simulations.
   */
  followUpsStopped?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Staff-led proposals and confirmed records. No calendar capacity or online payment is created.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  title: string;
  contact: number | Contact;
  enquiry: number | Enquiry;
  source: 'staff_enquiry';
  status: 'proposed' | 'confirmed' | 'completed' | 'cancelled';
  sessionAt?: string | null;
  /**
   * Expected value in minor currency units. Separate from money actually recorded.
   */
  expectedMinor: number;
  currency: string;
  attribution:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manual records only. Corrections append a reversal and replacement; no payment provider is called.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revenue-entries".
 */
export interface RevenueEntry {
  id: number;
  label: string;
  booking: number | Booking;
  contact: number | Contact;
  kind: 'payment' | 'refund' | 'reversal';
  amountMinor: number;
  currency: string;
  reverses?: (number | null) | RevenueEntry;
  occurredAt: string;
  reason: string;
  actor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dated private facts. Staff-reported replies are not an imported mailbox.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-activities".
 */
export interface CustomerActivity {
  id: number;
  contact: number | Contact;
  enquiry?: (number | null) | Enquiry;
  booking?: (number | null) | Booking;
  emailMessage?: (number | null) | EmailMessage;
  actor?: (number | null) | User;
  kind: string;
  summary: string;
  source: 'website' | 'staff' | 'provider' | 'migration' | 'system';
  occurredAt: string;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Exact frozen content. Drafts are not scheduled; accepted is not delivered, and delivered is not read.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-messages".
 */
export interface EmailMessage {
  id: number;
  contact: number | Contact;
  enquiry?: (number | null) | Enquiry;
  booking?: (number | null) | Booking;
  template?: (number | null) | EmailTemplate;
  kind: 'customer_draft' | 'sandbox_test' | 'photographer_notification';
  status:
    | 'draft'
    | 'queued'
    | 'sending'
    | 'accepted'
    | 'delayed'
    | 'delivered'
    | 'bounced'
    | 'failed'
    | 'uncertain'
    | 'manual'
    | 'disabled';
  subject: string;
  text: string;
  html: string;
  variables:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  templateSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recipient: string;
  sender?: string | null;
  providerPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  idempotencyKey?: string | null;
  notificationKey?: string | null;
  providerId?: string | null;
  attempts: number;
  firstAttemptAt?: string | null;
  lastAttemptAt?: string | null;
  acceptedAt?: string | null;
  deliveredAt?: string | null;
  /**
   * Safe category only; arbitrary provider responses are not stored.
   */
  failureCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Preview/edit never sends. Approval is for the wording; real-customer delivery remains disabled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  name: string;
  kind: 'enquiry' | 'booking' | 'follow_up';
  subject: string;
  /**
   * Plain text with allowed variables. HTML and external assets are not interpreted.
   */
  body: string;
  /**
   * I have reviewed this wording. Changing approved content clears approval. Save the change, review it, then approve again.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private test plans. Use the guided Follow-ups view. No automatic or real-customer delivery is active.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follow-ups".
 */
export interface FollowUp {
  id: number;
  contact: number | Contact;
  enquiry: number | Enquiry;
  booking?: (number | null) | Booking;
  template: number | EmailTemplate;
  rule?: (number | null) | FollowUpRule;
  purpose: 'enquiry_followup' | 'preparation' | 'session_reminder';
  triggerKey: string;
  triggeredAt: string;
  revision: number;
  plannedAt: string;
  timeZone: string;
  sessionSnapshot?: string | null;
  recipient: string;
  subject: string;
  text: string;
  html: string;
  templateSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state: 'planned' | 'blocked' | 'paused' | 'cancelled' | 'simulated' | 'failed';
  blockReason?: string | null;
  jobID?: number | null;
  attempts: number;
  outcomeKey?: string | null;
  simulatedAt?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Test planning only. No example is enabled by default and approval never enables live delivery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follow-up-rules".
 */
export interface FollowUpRule {
  id: number;
  name: string;
  purpose: 'enquiry_followup' | 'preparation' | 'session_reminder';
  template: number | EmailTemplate;
  /**
   * Elapsed hours after a proposal, or before the confirmed session. These are not business days.
   */
  hours: number;
  /**
   * Explicit IANA timezone for the planned-message display.
   */
  timeZone: string;
  /**
   * I reviewed the wording and elapsed-hour timing for test planning only.
   */
  approvedForTests?: boolean | null;
  revision: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Simulation or explicitly verified provenance. Real receiving remains unconfigured.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incoming-replies".
 */
export interface IncomingReply {
  id: number;
  eventKey: string;
  summary: string;
  contact?: (number | null) | Contact;
  enquiry?: (number | null) | Enquiry;
  source: 'simulation' | 'verified_provider';
  state: 'matched' | 'review';
  occurredAt: string;
  text?: string | null;
  reviewReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'simulateFollowUp';
        taskID: string;
        input:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: ('inline' | 'simulateFollowUp') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'simulateFollowUp') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processingUntil?: string | null;
  processingToken?: string | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'revenue-entries';
        value: number | RevenueEntry;
      } | null)
    | ({
        relationTo: 'customer-activities';
        value: number | CustomerActivity;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'email-messages';
        value: number | EmailMessage;
      } | null)
    | ({
        relationTo: 'follow-ups';
        value: number | FollowUp;
      } | null)
    | ({
        relationTo: 'follow-up-rules';
        value: number | FollowUpRule;
      } | null)
    | ({
        relationTo: 'incoming-replies';
        value: number | IncomingReply;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  visibility?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
      };
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  image?: T;
  imageSide?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  label?: T;
  href?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  contact?: T;
  serviceId?: T;
  serviceTitle?: T;
  name?: T;
  email?: T;
  message?: T;
  followUp?: T;
  submissionHash?: T;
  contentHash?: T;
  attribution?: T;
  notificationStatus?: T;
  notificationAttempts?: T;
  notificationAttemptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  notes?: T;
  sourceKey?: T;
  followUpsStopped?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  title?: T;
  contact?: T;
  enquiry?: T;
  source?: T;
  status?: T;
  sessionAt?: T;
  expectedMinor?: T;
  currency?: T;
  attribution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revenue-entries_select".
 */
export interface RevenueEntriesSelect<T extends boolean = true> {
  label?: T;
  booking?: T;
  contact?: T;
  kind?: T;
  amountMinor?: T;
  currency?: T;
  reverses?: T;
  occurredAt?: T;
  reason?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-activities_select".
 */
export interface CustomerActivitiesSelect<T extends boolean = true> {
  contact?: T;
  enquiry?: T;
  booking?: T;
  emailMessage?: T;
  actor?: T;
  kind?: T;
  summary?: T;
  source?: T;
  occurredAt?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  subject?: T;
  body?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-messages_select".
 */
export interface EmailMessagesSelect<T extends boolean = true> {
  contact?: T;
  enquiry?: T;
  booking?: T;
  template?: T;
  kind?: T;
  status?: T;
  subject?: T;
  text?: T;
  html?: T;
  variables?: T;
  templateSnapshot?: T;
  recipient?: T;
  sender?: T;
  providerPayload?: T;
  idempotencyKey?: T;
  notificationKey?: T;
  providerId?: T;
  attempts?: T;
  firstAttemptAt?: T;
  lastAttemptAt?: T;
  acceptedAt?: T;
  deliveredAt?: T;
  failureCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follow-ups_select".
 */
export interface FollowUpsSelect<T extends boolean = true> {
  contact?: T;
  enquiry?: T;
  booking?: T;
  template?: T;
  rule?: T;
  purpose?: T;
  triggerKey?: T;
  triggeredAt?: T;
  revision?: T;
  plannedAt?: T;
  timeZone?: T;
  sessionSnapshot?: T;
  recipient?: T;
  subject?: T;
  text?: T;
  html?: T;
  templateSnapshot?: T;
  state?: T;
  blockReason?: T;
  jobID?: T;
  attempts?: T;
  outcomeKey?: T;
  simulatedAt?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follow-up-rules_select".
 */
export interface FollowUpRulesSelect<T extends boolean = true> {
  name?: T;
  purpose?: T;
  template?: T;
  hours?: T;
  timeZone?: T;
  approvedForTests?: T;
  revision?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incoming-replies_select".
 */
export interface IncomingRepliesSelect<T extends boolean = true> {
  eventKey?: T;
  summary?: T;
  contact?: T;
  enquiry?: T;
  source?: T;
  state?: T;
  occurredAt?: T;
  text?: T;
  reviewReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  meta?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processingUntil?: T;
  processingToken?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'users'
      | 'media'
      | 'pages'
      | 'enquiries'
      | 'contacts'
      | 'bookings'
      | 'revenue-entries'
      | 'customer-activities'
      | 'email-templates'
      | 'email-messages'
      | 'follow-ups'
      | 'follow-up-rules'
      | 'incoming-replies';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'users'
          | 'media'
          | 'pages'
          | 'enquiries'
          | 'contacts'
          | 'bookings'
          | 'revenue-entries'
          | 'customer-activities'
          | 'email-templates'
          | 'email-messages'
          | 'follow-ups'
          | 'follow-up-rules'
          | 'incoming-replies'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSimulateFollowUp".
 */
export interface TaskSimulateFollowUp {
  input: {
    plan: number;
    revision: number;
  };
  output: {
    state: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}